### ISSUE TITLE
Building schema error when running project with NPM

### ISSUE THREAD

**Issue by mikeesto** [graphql/graphql.github.io#946] opened 2020-11-03 05:34 UTC
When trying to `npm install && npm start`:

<img width="809" alt="Screen Shot 2020-11-03 at 2 57 30 pm" src="https://user-images.githubusercontent.com/21051488/97952005-c124d700-1de7-11eb-9622-1e360b19cf2c.png">

There seems to be some related discussion about it [here](https://github.com/gatsbyjs/gatsby/issues/13278) although there's no resolution. I ended up deleting node_modules & package-lock.json, and using yarn.

**Comment by carolstran** [comment] 2020-11-16 14:31
@mikeesto I also ran into this the first time I launched the site post-Gatsby migration. I'm working on a new contributing guide and thinking of only encouraging the use of `yarn` for now since there's no resolution on the Gatsby end 🤷🏼‍♀️

**Comment by orta** [comment] 2020-11-16 14:34
Yep, we should drop the npm installation recommendations - they don't get the lockfile and will definitely have different builds which would cause random issues like this

**Comment by Urigo** [comment] 2023-04-09 18:19
@TuvalSimha is this still relevant?

**Comment by TuvalSimha** [comment] 2023-04-10 08:51
@Urigo 
I was trying to reproduce it:
1. `npm install`
2. `npm start`

The build was created and the project was running properly. You can close this issue for this moment.

**Comment by Urigo** [comment] 2023-04-11 13:53
thanks!
solved, please reopen if happens again

**Closed by Urigo** 2023-04-11 13:53 UTC
Labels: 🐛 Bug, 📦 Dependencies
