### ISSUE TITLE
Create a new Learn section for Subscriptions

### ISSUE THREAD

**Issue by carolstran** [graphql/graphql.github.io#993] opened 2020-12-21 19:57 UTC
### Description

Currently, the [Learn section of graphql.org](https://graphql.org/learn/) doesn't include any information about subscriptions. Right now, it's only in the specification, and that includes details for [how to write and execute subscriptions](https://spec.graphql.org/draft/#sec-Subscription).

It'd be great if we could get a section going and add some walk-throughs and tutorials so people can learn how to work with subscriptions 🎉

**Comment by j0k3r** [comment] 2021-01-08 14:46
Duplicate of #584

**Comment by SURAJITSHAW** [comment] 2021-09-12 17:56
Hello I really like to work on this. But I have a question after adding a subsection 'subscription' to learn section, I just add the contents that are here [https://spec.graphql.org/draft/#sec-Subscription](url) to the 'subscription'. Is it Okay ?

**Comment by hwillson** [comment] 2022-11-13 00:36
As @j0k3r mentioned in https://github.com/graphql/graphql.github.io/issues/993#issuecomment-756792639, this is a duplicate of https://github.com/graphql/graphql.github.io/issues/584. Let's continue the discussion in that issue. Thanks!

**Closed by hwillson** 2022-11-13 00:36 UTC
Labels: 📌 Help wanted, ✏️ Editorial
